### 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([ 76, 139,   5,  17, 127,  68,  89,  44,  39,  61,  42,  71,   1,
        52, 145,  67, 124,  57, 100, 129,  11,  75,  69, 108,  94,  15,
        43,  77, 109,  47,  21, 142,  48,  51,  72, 149,  88, 114,   7,
        37, 120,  60,   3, 115, 118,  80,  26, 123,   2,  63,  96, 138,
       135,  85,  46, 132, 130, 116,  19,  86, 111,  10,  79,  28, 137,
       140,  22,  62,  84, 112, 101,  92,  97,  73,  55,  50, 122,  30,
       110,  90, 119,  64, 131,  98, 136,  29,  23,  81,  49,  65, 134,
        70, 104,  99,  93, 103,  34,  45, 144,   0,  59,  56,  78,  95,
        53,  32,  14,   4, 147, 106,  91, 102,  24,  36,  41,  25,  87,
        83,  31, 143,  27,  82, 117, 107,  13, 121, 113,  33,  54, 105,
        16,  58,  40,   9,  18,  74, 146,  38,  20,  66, 148, 133, 141,
        12, 126,   6, 128,  35,   8, 125])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 使用我们的算法

In [15]:
from playML.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [18]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [21]:
from playML.KNN import KNNClassifier

In [22]:
my_knn_clf = KNNClassifier(k=3)

In [23]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [24]:
y_predict = my_knn_clf.predict(X_test)

In [25]:
y_predict

array([2, 2, 2, 1, 1, 2, 0, 2, 2, 1, 1, 2, 0, 2, 1, 0, 1, 2, 0, 2, 0, 0,
       2, 2, 2, 2, 1, 2, 2, 0])

In [26]:
y_test

array([2, 2, 2, 1, 1, 2, 0, 2, 2, 1, 2, 2, 0, 2, 1, 0, 1, 2, 0, 2, 0, 0,
       2, 2, 2, 2, 1, 2, 2, 0])

In [27]:
sum(y_predict == y_test)

29

In [28]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [31]:
from sklearn.model_selection import train_test_split

In [38]:
# random_state为随机种子
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [41]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [42]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
