### %run

In [1]:
%run Demo/test1.py

19.0


In [2]:
%timeit L = [i**2 for i in range(1000)]

931 µs ± 120 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%time L = [i**2 for i in range(100000)]

Wall time: 108 ms


In [4]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [1]:
import numpy as np

In [6]:
nparr = np.array([i for i in range(10)])

In [7]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
nparr[5]

5

In [9]:
nparr.dtype

dtype('int32')

In [10]:
nparr2 = np.array([1,2,3.0])

In [11]:
nparr2.dtype

dtype('float64')

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Linspace

In [13]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [14]:
np.linspace(0, 20 ,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [15]:
np.random.randint(0, 10)

2

In [16]:
np.random.randint(0, 10, 10)

array([8, 1, 5, 8, 8, 2, 1, 0, 9, 0])

In [17]:
np.random.randint(4, 8, size=10)

array([4, 6, 5, 6, 6, 6, 7, 6, 7, 6])

In [18]:
np.random.randint(4, 8, size=(3, 5))

array([[5, 6, 4, 6, 6],
       [7, 4, 7, 7, 5],
       [6, 4, 7, 7, 7]])

In [19]:
np.random.normal()

-0.371192417107635

In [20]:
# 符合正态分布
np.random.normal(10, 100)

-56.988024418659265

In [21]:
np.random.normal(0, 1, (3, 5))

array([[ 2.10573107, -1.34760361,  0.45815593,  1.05403314, -0.88169039],
       [-0.22367701, -2.09376394,  0.71584233,  0.00979046,  0.48523384],
       [ 0.31701912,  1.03386515, -0.16854063, -1.32321214,  0.81211846]])

In [22]:
np.random.random(10)

array([0.1541923 , 0.91930666, 0.43070085, 0.94441803, 0.81025381,
       0.15904112, 0.76984211, 0.89576102, 0.56115229, 0.55366123])

In [23]:
np.random.random((3, 5))

array([[0.02846493, 0.15058026, 0.01308884, 0.3332749 , 0.67831558],
       [0.84139888, 0.98711678, 0.37294159, 0.48731457, 0.30986715],
       [0.78009362, 0.78441744, 0.39297017, 0.75111086, 0.54607526]])

In [24]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [25]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [27]:
x.ndim

2

In [28]:
X.ndim

1

In [29]:
x.shape

(3, 5)

In [30]:
X.shape

(10,)

In [31]:
x.size

15

In [32]:
X.size

10

### numpy.array 的数据访问

In [33]:
x 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
X[0] 
X[-1]

9

In [36]:
x[2, 2]

12

In [37]:
x[0, 0]

0

In [38]:
x[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
X[0:5]

array([0, 1, 2, 3, 4])

In [40]:
x[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
X[::2]

array([0, 2, 4, 6, 8])

In [42]:
X[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [44]:
x[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
x[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [46]:
x[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [47]:
x[0]

array([0, 1, 2, 3, 4])

In [48]:
# 取一行
x[0, :]

array([0, 1, 2, 3, 4])

In [49]:
x[0, :].ndim

1

In [50]:
# 取一列
x[:, 0]

array([ 0,  5, 10])

In [51]:
subx = x[:2, :3]

In [52]:
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [53]:
subx[0, 0] = 100

In [54]:
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [55]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [56]:
x[0, 0] = 0
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
subx = x[:2, :3].copy()
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [58]:
subx[0, 0] = 100
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [59]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [60]:
X.shape

(10,)

In [61]:
X.ndim

1

In [62]:
X.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
A = X.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
B = X.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
B.ndim

2

In [67]:
B.shape

(1, 10)

In [68]:
X.shape

(10,)

In [69]:
X.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [70]:
X.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
X.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [72]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [73]:
x

array([1, 2, 3])

In [74]:
y

array([3, 2, 1])

In [75]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [76]:
z = np.array([666, 666, 666])

In [77]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [78]:
A = np.array([[1,2,3],[4,5,6]])

In [79]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [81]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [82]:
np.concatenate([A, A], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [84]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [86]:
# 合并 即使维度不同
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [87]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [88]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [89]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x1, x2, x3 = np.split(x, [3, 7])

In [91]:
x1

array([0, 1, 2])

In [92]:
x2

array([3, 4, 5, 6])

In [93]:
x3

array([7, 8, 9])

In [94]:
x1, x2 = np.split(x, [5])

In [95]:
x1

array([0, 1, 2, 3, 4])

In [96]:
x2

array([5, 6, 7, 8, 9])

In [97]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
# 上下分割
A1, A2 = np.split(A, [2])

In [99]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
# 左右分割
A1, A2 = np.split(A, [3], axis=1)

In [102]:
A1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [103]:
A2

array([[ 3],
       [ 7],
       [11],
       [15]])

In [104]:
upper, lowwer = np.vsplit(A, [2])

In [105]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [106]:
lowwer

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
left, right = np.hsplit(A, [2])

In [108]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [109]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [110]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
X, y = np.hsplit(data, [-1])

In [112]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [113]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [114]:
# 列转行
y[:, 0]

array([ 3,  7, 11, 15])

### 聚合操作

In [115]:
L = np.random.random(100)

In [116]:
L

array([0.02204994, 0.43638537, 0.48399744, 0.97580535, 0.60528695,
       0.44119218, 0.11668164, 0.15519717, 0.11702176, 0.49375051,
       0.54388051, 0.38475279, 0.76370618, 0.91854091, 0.94798395,
       0.44668555, 0.5545782 , 0.94122832, 0.93453175, 0.32552796,
       0.79352375, 0.46092513, 0.45683081, 0.75856479, 0.63950432,
       0.22309942, 0.83013975, 0.00781993, 0.12696062, 0.46445168,
       0.18690779, 0.39120155, 0.28872914, 0.55115839, 0.55693885,
       0.22222732, 0.96715338, 0.27330302, 0.33087597, 0.99977176,
       0.1397086 , 0.08238756, 0.1598267 , 0.41942417, 0.75235473,
       0.90273555, 0.39874397, 0.12605372, 0.75084286, 0.75460296,
       0.49425244, 0.93708435, 0.01971055, 0.22322801, 0.2163424 ,
       0.19850755, 0.19616897, 0.95068229, 0.95965189, 0.04772338,
       0.98560765, 0.22063394, 0.98614555, 0.32691931, 0.79526589,
       0.03060302, 0.78972893, 0.52368594, 0.37982449, 0.41001715,
       0.04492399, 0.22840746, 0.71627281, 0.31176774, 0.83389

In [117]:
sum(L)

50.46457134067862

In [118]:
np.sum(L)

50.46457134067862

In [119]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

269 ms ± 14.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.25 ms ± 186 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [120]:
np.min(big_array)

1.3084326571100036e-06

In [121]:
np.max(big_array)

0.9999990335459648

In [122]:
big_array.min()

1.3084326571100036e-06

In [123]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [125]:
np.array(16)

array(16)

In [126]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
np.sum(X)

120

In [128]:
# 列
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [130]:
# 行
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [131]:
# 乘积
np.prod(x)

0

In [136]:
np.prod(X + 1)

2004189184

In [133]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.mean(x)

4.5

In [139]:
np.median(x)

4.5

In [140]:
# 均值
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [141]:
# 中位数
np.median(v)

2.0

In [145]:
# 百分位
np.percentile(big_array, q=50)

0.49955437249906987

In [146]:
np.percentile(big_array, q=100)

0.9999990335459648

In [147]:
np.max(big_array)

0.9999990335459648

In [148]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.3084326571100036e-06
0.25013933383808906
0.49955437249906987
0.7507354209193894
0.9999990335459648


In [149]:
# 方差
np.var(big_array)

0.08337391006674585

In [150]:
# 标准差
np.std(big_array)

0.288745407005455

In [151]:
# 均值为0，标准差为1
x = np.random.normal(0, 1, size=1000000)

In [152]:
np.mean(x)

-0.002557992119378889

In [153]:
np.std(x)

1.000579531608286

### 索引

In [154]:
np.min(x)

-4.763387353034611

In [155]:
# 返回最小的索引
np.argmin(x)

569022

In [156]:
x[569022]

-4.763387353034611

In [157]:
# 最大值索引
np.argmax(x)

580438

In [158]:
x[580438]

4.960284770915608

In [159]:
np.max(x)

4.960284770915608

### 排序和使用索引

In [160]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [162]:
# 乱序处理
np.random.shuffle(x)
x

array([10,  6,  9,  8, 13, 15,  4,  2, 11,  0,  1, 14,  5,  3, 12,  7])

In [167]:
# x本身未改变
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [168]:
x

array([10,  6,  9,  8, 13, 15,  4,  2, 11,  0,  1, 14,  5,  3, 12,  7])

In [169]:
# x改变
x.sort()

In [170]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [171]:
X = np.random.randint(10, size=(4, 4))
X

array([[7, 8, 7, 2],
       [3, 1, 9, 1],
       [4, 9, 6, 1],
       [7, 1, 4, 6]])

In [172]:
# 将每一行排序,axis默认为1
np.sort(X)

array([[2, 7, 7, 8],
       [1, 1, 3, 9],
       [1, 4, 6, 9],
       [1, 4, 6, 7]])

In [173]:
np.sort(X, axis=1)

array([[2, 7, 7, 8],
       [1, 1, 3, 9],
       [1, 4, 6, 9],
       [1, 4, 6, 7]])

In [174]:
np.sort(X, axis=0)

array([[3, 1, 4, 1],
       [4, 1, 6, 1],
       [7, 8, 7, 2],
       [7, 9, 9, 6]])

In [175]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [176]:
np.random.shuffle(x)

In [177]:
x

array([ 1, 15,  9, 14, 12, 11,  5, 13,  6,  3,  7,  0, 10,  4,  2,  8])

In [178]:
# 返回原array中的索引，从小到大排序
np.argsort(x)

array([11,  0, 14,  9, 13,  6,  8, 10, 15,  2, 12,  5,  4,  7,  3,  1],
      dtype=int64)

In [179]:
# 标定点 ,比3小往左排 比3大往右排
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  7,  5,  6,  8, 15, 11, 12, 10, 14,  9, 13])

In [180]:
# 索引
np.argpartition(x, 3)

array([11,  0, 14,  9, 13, 10,  6,  8, 15,  1,  5,  4, 12,  3,  2,  7],
      dtype=int64)

In [185]:
np.argwhere(x==3)

array([[9]], dtype=int64)

In [187]:
X

array([[7, 8, 7, 2],
       [3, 1, 9, 1],
       [4, 9, 6, 1],
       [7, 1, 4, 6]])

In [188]:
np.argsort(X, axis=1)

array([[3, 0, 2, 1],
       [1, 3, 0, 2],
       [3, 0, 2, 1],
       [1, 2, 3, 0]], dtype=int64)

In [189]:
np.argsort(X, axis=0)

array([[1, 1, 3, 1],
       [2, 3, 2, 2],
       [0, 0, 0, 0],
       [3, 2, 1, 3]], dtype=int64)

In [191]:
np.argpartition(X, 2, axis=1)

array([[3, 2, 0, 1],
       [1, 3, 0, 2],
       [3, 0, 2, 1],
       [1, 2, 3, 0]], dtype=int64)

### Fancy Indexing

In [194]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [195]:
x[3]

3

In [196]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [197]:
x[3:9:2]

array([3, 5, 7])

In [198]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [199]:
ind = [3, 5, 8]

In [200]:
x[ind]

array([3, 5, 8])

In [202]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [203]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [204]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])

In [205]:
X[row, col]

array([ 1,  6, 11])

In [206]:
X[0, col]

array([1, 2, 3])

In [207]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [208]:
col = [True, False, True, True]

In [209]:
X[1: 3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array的比较

In [210]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [211]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [212]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [213]:
2*x == 24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [214]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [215]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [216]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [217]:
np.sum(x <= 3)

4

In [218]:
np.count_nonzero(x<=3)

4

In [219]:
np.any(x==0)

True

In [220]:
np.any(x+1 ==0)

False

In [221]:
np.any(x < 0)

False

In [222]:
np.all(x >= 0)

True

In [223]:
np.all(x > 0)

False

In [224]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [225]:
np.sum(X % 2 == 0)

8

In [226]:
np.sum(X%2 == 0, axis=1)

array([2, 2, 2, 2])

In [227]:
np.sum(X%2 == 0, axis=0)

array([4, 0, 4, 0])

In [228]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [229]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [230]:
np.sum((x > 3) & (x < 10))

6

In [231]:
np.sum((x % 2 ==0) | (x > 10))

11

In [232]:
np.sum(~(x==0))

15

In [233]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [234]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [235]:
X[X[:,3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### (Pandas)