In [1]:
img1 = r'D:\Demo\JD_Snap_up\temp\1.png'
img2 = r'D:\Demo\JD_Snap_up\temp\2.png'
import cv2
import numpy as np

In [12]:
src = cv2.imread(img1)
target = cv2.imread(img2)
h1, w1, _ = src.shape
h2, w2, _ = target.shape
src = src[0:h1, w2:w1]
blurred = cv2.GaussianBlur(src, (5, 5), 0)
blurred2 = cv2.GaussianBlur(target, (3,3), 0)
gray = cv2.cvtColor(blurred, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(blurred2, cv2.COLOR_BGR2GRAY)
edge_output = cv2.Canny(gray, 50, 150)
edge_output2 = cv2.Canny(gray2, 50, 150)

In [13]:
cv2.imshow('gary1',edge_output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
cv2.imshow('gary1',edge_output2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
result = cv2.matchTemplate(edge_output, edge_output2, cv2.TM_CCOEFF_NORMED)
x, y = np.unravel_index(result.argmax(), result.shape)

In [18]:
y

192

In [15]:
lines = cv2.HoughLinesP(edge_output, 1, np.pi / 180, 20, minLineLength=15, maxLineGap=8)

In [18]:
print(lines[:, 0, :])
print(lines)

[[  2   1 277   1]
 [  1 107   1   2]
 [ 97 100 169  81]
 [143  76 162  81]
 [199  73 199  42]
 [232  45 232   2]
 [  2  87  22  81]
 [ 17  53  37  58]
 [249  11 250  28]
 [224  67 249  59]
 [173  83 190  87]
 [143  77 154  62]
 [176  54 193  52]
 [193  23 211  25]
 [174  48 203  25]
 [  7  71  35  68]
 [153  83 172  93]
 [  5  68  26  65]
 [262  16 262  31]
 [167  47 182  26]
 [167  46 182  25]
 [194  34 201  18]
 [  3  65  28  62]
 [146  76 172  82]
 [176  49 198  41]
 [155  80 176  75]
 [231  24 231   2]
 [  3  66  27  64]]
[[[  2   1 277   1]]

 [[  1 107   1   2]]

 [[ 97 100 169  81]]

 [[143  76 162  81]]

 [[199  73 199  42]]

 [[232  45 232   2]]

 [[  2  87  22  81]]

 [[ 17  53  37  58]]

 [[249  11 250  28]]

 [[224  67 249  59]]

 [[173  83 190  87]]

 [[143  77 154  62]]

 [[176  54 193  52]]

 [[193  23 211  25]]

 [[174  48 203  25]]

 [[  7  71  35  68]]

 [[153  83 172  93]]

 [[  5  68  26  65]]

 [[262  16 262  31]]

 [[167  47 182  26]]

 [[167  46 182  25]]

 [[19

In [19]:
cv2.imshow('gary1',lines)
cv2.waitKey(0)

error: OpenCV(4.4.0) C:/Users/appveyor/AppData/Local/Temp/1/pip-req-build-52oirelq/opencv/modules/highgui/src/precomp.hpp:137: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'


In [10]:
cv2.imshow('gary1',gary1)
cv2.waitKey(0)
cv2.destroyAllWindows()

27

In [18]:
otemp = img1
oblk = img2
target = cv2.imread(otemp, 0)
template = cv2.imread(oblk, 0)
h, w = target.shape
temp = r'D:\Demo\JD_Snap_up\temp\3.png'
targ = r'D:\Demo\JD_Snap_up\temp\4.png'
target = cv2.imread(targ)
target = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)
target = abs(255 - target)
cv2.imwrite(targ, target)
target = cv2.imread(targ)
template = cv2.imread(temp)
template = template[0:108, 39:278]
result = cv2.matchTemplate(target, template, cv2.TM_CCOEFF_NORMED)
x, y = np.unravel_index(result.argmax(), result.shape)
# 展示圈出来的区域
cv2.rectangle(template, (y, x), (y + w, x + h), (7, 249, 151), 2)
cv2.imshow('temp', template)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
cv2.imshow('temp', template)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
target.shape

(39, 39, 3)

In [12]:
template.shape
template[0:108, 39:278]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[ 53,  53,  53],
        [ 53,  53,  53],
        [ 50,  50,  50],
        ...,
        [106, 106, 106],
        [112, 112, 112],
        [165, 165, 165]],

       [[ 53,  53,  53],
        [ 53,  53,  53],
        [ 53,  53,  53],
        ...,
        [102, 102, 102],
        [102, 102, 102],
        [102, 102, 102]],

       ...,

       [[ 64,  64,  64],
        [ 64,  64,  64],
        [ 64,  64,  64],
        ...,
        [218, 218, 218],
        [215, 215, 215],
        [  7, 249, 151]],

       [[ 64,  64,  64],
        [ 64,  64,  64],
        [ 66,  66,  66],
        ...,
        [219, 219, 219],
        [218, 218, 218],
        [  7, 249, 151]],

       [[ 64,  64,  64],
        [ 64,  64,  64],
        [ 64,  64,  64],
        ...,
        [218, 218, 218],
        [216, 216, 216],
        [  7, 249, 151]]

In [20]:
cv2.imshow('temp', target)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
cv2.imwrite(targ, target)

True

In [22]:
a1 = cv2.imread(img1, 0)
a2 = cv2.imread(img2, 0)

h1, w1 = a1.shape
h2, w2 = a2.shape
cv2.imwrite(temp, template[0:h1, w2:w1])


True

In [19]:
# 获取图片并灰度化
block = cv2.imread(img1, 0)
template = cv2.imread(img2, 0)
# 二值化后的图片名称
blockName = r'D:\Demo\JD_Snap_up\temp\5.png'
templateName = r'D:\Demo\JD_Snap_up\temp\6.png'
# 将二值化后的图片进行保存
cv2.imwrite(r'D:\Demo\JD_Snap_up\temp\5.png', block)
cv2.imwrite(r'D:\Demo\JD_Snap_up\temp\6.png', template)
block = cv2.imread(blockName)
block = cv2.cvtColor(block, cv2.COLOR_RGB2GRAY)
block = abs(255 - block)
cv2.imwrite(blockName, block)
block = cv2.imread(blockName)
template = cv2.imread(templateName)
# 获取偏移量
result = cv2.matchTemplate(block, template, cv2.TM_CCOEFF_NORMED) # 查找block在template中的位置，返回result是一个矩阵，是每个点的匹配结果
x, y = np.unravel_index(result.argmax(), result.shape)

In [44]:
x

39

In [45]:
y

0

In [36]:
block = cv2.imread(blockName)
block = cv2.cvtColor(block, cv2.COLOR_RGB2GRAY)
block = abs(255 - block)

In [41]:
block = cv2.imread(img1, 0)
template = cv2.imread(img2, 0)

In [42]:
cv2.imshow('temp', block)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
result = cv2.matchTemplate(block, template, cv2.TM_CCOEFF_NORMED)
x, y = np.unravel_index(result.argmax(), result.shape)